Project2/Controllers/ProcedureController.cs
using Microsoft.Reporting.WebForms;
using Project2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2.Controllers
{
    public class ProcedureController : Controller
    {
        Pathology_dbEntities1 db = new Pathology_dbEntities1();
        // GET: Procedure
        public ActionResult Indexx()
        {
            return View();
        }

        public ActionResult order()
        {

            List<TBL_MASTER_PROCEDURE> OrderAndCustomerList = db.TBL_MASTER_PROCEDURE.ToList();
            return View(OrderAndCustomerList);
           
        }
        public JsonResult getprocedure(string MRNO)
        {
            //List<int> li = db.TBL_R_PATIENT.Where(x => x.MR_NO.ToString().Equals("10")).Select(y => y.MR_NO).ToList();

            var lii = db.TBL_MASTER_PRO_ENTRY.Where(x => x.PRO_NAME.ToString().Equals(MRNO)).Select(x => new
            {
                name = x.PRO_NAME,
                id = x.PRO_ID,
                price = x.PRO_PRICE,
                cat = x.PRO_CAT

            }).ToList();
            return Json(lii, JsonRequestBehavior.AllowGet);
        }
            public JsonResult ProcedureENT(string searchTerm)
        {

            var pateint = db.TBL_MASTER_PRO_ENTRY.Where(x => x.PRO_NAME.Contains(searchTerm)).ToList();
            var aa = pateint.Select(x => new
            {
                id = x.PRO_NAME,
                text = x.PRO_NAME
                //,
                //price=x.PRO_PRICE
                //text =  x.FIRST_NAME 
            });
            return Json(aa, JsonRequestBehavior.AllowGet);
        }


        public ActionResult SaveOrder(int mr, int cons, TBL_MPROC_DETAIL[] order)
        {
            string result = "Error! Order Is Not Complete!";
            if (mr != 0 && cons != 0)
            {
                //int cutomerId = Guid.NewGuid();
                TBL_MASTER_PROCEDURE model = new TBL_MASTER_PROCEDURE();
                model.MR = mr;
                model.MP_CONS = cons;
                model.MP_USER_ID = Convert.ToInt32(Session["user_id"]);
                model.MP_USER_ORG= Convert.ToInt32(Session["user_org"]);
                model.MP_USER_dATE = DateTime.Now;
                db.TBL_MASTER_PROCEDURE.Add(model);
                db.SaveChanges();
                int last_insert_id = model.MP_CODE;
                foreach (var item in order)
                {
                    //var orderId = Guid.NewGuid();
                    TBL_MPROC_DETAIL tmd = new TBL_MPROC_DETAIL();
                    //O.OrderId = orderId;
                    tmd.MP_CODE = last_insert_id;
                    tmd.pro_id = item.pro_id;
                    tmd.PRICE = item.PRICE;
                    db.TBL_MPROC_DETAIL.Add(tmd);
                }
                db.SaveChanges();

            }
           
            result = "Success! Order Is Complete!";
            
            return Json(result, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("reporting");

        }










        public ActionResult Entry_Proc()
        {
            Pathology_dbEntities1 db = new Pathology_dbEntities1();
            ViewBag.PANEL = new SelectList(db.TBL_R_PANEL, "PANEL_ID", "PANEL_NAME");
            ViewBag.consultants = new SelectList(db.TBL_PAY_MAST, "EMP_CODE", "EMP_NAME");
            ViewBag.gendr = new SelectList(db.TBL_Gender, "G_id", "G_name");
            return View();
        }

        public ActionResult Index()

        {

            Pathology_dbEntities1 db = new Pathology_dbEntities1();
            return View(db.TBL_R_DEPT);
        }

        public ActionResult Bank()
        {
            return View();
        }


        public JsonResult InsertCustomers(List<TBL_MPROC_DETAIL> customers)
        {
            using( Pathology_dbEntities1 db = new Pathology_dbEntities1())
            {
                TBL_MASTER_PROCEDURE mp =  new TBL_MASTER_PROCEDURE();
                //Truncate Table to delete all old records.
                db.Database.ExecuteSqlCommand("TRUNCATE TABLE [TBL_MPROC_DETAIL]");
                //Check for NULL.
                if (customers == null)
                {
                    customers = new List<TBL_MPROC_DETAIL>();
                }

                //Loop and insert records.
                foreach (TBL_MPROC_DETAIL customer in customers)
                {
                    db.TBL_MPROC_DETAIL.Add(customer);
                }
                int insertedRecords = db.SaveChanges();
                return Json(insertedRecords);
            }








        }


        public ActionResult reporting()
        {
            int sub = 36;
            string id = ".pdf";
            var lr = new LocalReport();
            String path = Path.Combine(Server.MapPath("~/Report"), "ProSlip.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;

            }
            else
            {
                return View("index");
            }
            List<Procedure_slip> att = new List<Procedure_slip>();
            using (Pathology_dbEntities1 entities = new Pathology_dbEntities1())
            {
                att = entities.Procedure_slip.Where(a => a.mp_code == sub).ToList();
            }
            ReportDataSource rds = new ReportDataSource("DataSet1", att);
            lr.DataSources.Add(rds);
            string reporttype = id;
            string minetype;
            string encoding;
            string filenameextension = id;
            string deviceinfo =
            "<DeviceInfo>" +
                "<OutputFormat>DD</OutputFormat>" +
                "<PageWidth>8.5in</PageWidth>" +
                "<PageHeight>11in</PageHeight>" +
                "<MarginTop>0.5in</MarginTop>" +
                "<MarginLeft>11in</MarginLeft>" +
                "<MarginRight>11in</MarginRight>" +
                "<MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";
            Warning[] warning;
            string[] stream;
            byte[] renderedbytes;
            renderedbytes = lr.Render("pdf", deviceinfo, out minetype, out encoding, out filenameextension, out stream, out warning);

            return File(renderedbytes, minetype);

        }
    }

}

Project2/Views/Procedure/Index.cshtml
@model IEnumerable<Project2.Models.TBL_R_DEPT>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>InsertCustomers</h2>

<table id="tblCustomers" class="table" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th style="width:150px">Name</th>
            <th style="width:150px">Country</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.DEPT_ID</td>
                <td>@customer.DEPT_NAME</td>
                <td><input type="button" value="Remove" onclick="Remove(this)" /></td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td><input type="text" id="txtName" /></td>
            <td><input type="text" id="txtCountry" /></td>
            <td><input type="button" id="btnAdd" value="Add" /></td>
        </tr>
    </tfoot>
</table>
<br />
<input type="button" id="btnSave" value="Save All" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
<script type="text/javascript">
    $("body").on("click", "#btnAdd", function () {
        //Reference the Name and Country TextBoxes.
        var txtName = $("#txtName");
        var txtCountry = $("#txtCountry");

        //Get the reference of the Table's TBODY element.
        var tBody = $("#tblCustomers > TBODY")[0];

        //Add Row.
        var row = tBody.insertRow(-1);

        //Add Name cell.
        var cell = $(row.insertCell(-1));
        cell.html(txtName.val());

        //Add Country cell.
        cell = $(row.insertCell(-1));
        cell.html(txtCountry.val());

        //Add Button cell.
        cell = $(row.insertCell(-1));
        var btnRemove = $("<input />");
        btnRemove.attr("type", "button");
        btnRemove.attr("onclick", "Remove(this);");
        btnRemove.val("Remove");
        cell.append(btnRemove);

        //Clear the TextBoxes.
        txtName.val("");
        txtCountry.val("");
    });

    function Remove(button) {
        //Determine the reference of the Row using the Button.
        var row = $(button).closest("TR");
        var name = $("TD", row).eq(0).html();
        if (confirm("Do you want to delete: " + name)) {
            //Get the reference of the Table.
            var table = $("#tblCustomers")[0];

            //Delete the Table row using it's Index.
            table.deleteRow(row[0].rowIndex);
        }
    };

    $("body").on("click", "#btnSave", function () {
        //Loop through the Table rows and build a JSON array.
        var customers = new Array();
        $("#tblCustomers TBODY TR").each(function () {
            var row = $(this);
            var customer = {};
            customer.Name = row.find("TD").eq(0).html();
            customer.Country = row.find("TD").eq(1).html();
            customers.push(customer);
        });

        //Send the JSON array to Controller using AJAX.
        $.ajax({
            type: "POST",
            url: "/Home/InsertCustomers",
            data: JSON.stringify(customers),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (r) {
                alert(r + " record(s) inserted.");
            }
        });
    });
</script>

Project2/Views/Procedure/order.cshtml
@model IEnumerable<Project2.Models.TBL_MASTER_PROCEDURE>

@{
    ViewBag.Title = "order";
     Layout = "~/Views/Shared/_Layout.cshtml";
   // Layout = null;

}

<br />
<br />
<div class="card">
    <div class="card-header card-header-primary">
        <h4 class="card-title"> Procedure Order </h4>
        <p class="card-category">Complete your profile</p>
    </div>
    <div class="row">
        <h2 class="panel-title pull-left" style="margin-left:10px;">
        </h2>
        @*<button style="margin-right:10px" class="btn btn-danger pull-right" href="~/procedure/Entry_Proc">New Order</button>*@


        <button type="button" style="margin-right:10px" class="btn btn-danger pull-right" onclick="location.href='@Url.Action("Entry_proc", "Procedure")'" />New Order</button>
    </div>








    <div class="panel panel-default">
        @if (Model.Count() != 0)
        {
            foreach (var item in Model)
            {
                <div class="panel-body">
                    <table class="table table-striped table-responsive">
                        <tbody>
                            <tr>
                                <td>Order No :<b> @item.MP_CODE </b></td>
                                <td>Patient MR No :<b> @item.MR </b></td>
                                <td>Patient  Name : <b> @item.TBL_R_PATIENT.FIRST_NAME </b></td>
                                <td>Patient Contact :<b> @item.TBL_R_PATIENT.TEL_NO </b></td>
                                <td>Address : <b> @item.MP_GRANT_TOTAL </b> </td>
                                <td>Address : <b>  </b> </td>
                                <td>Order Date : <b> @item.MP_USER_dATE </b></td>


                            </tr>
                            <tr>
                                <td colspan="3">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <th>Pro Code</th>
                                                <th>Pro Name </th>
                                                <th>Unit Price</th>
                                                <th>Quantity</th>
                                            </tr>
                                            @{
                                                var totalBill = 0;
                                            }
                                            @foreach (var order in item.TBL_MPROC_DETAIL)
                                            {
                                                <tr>
                                                    <td>@order.pro_id</td>
                                                    <td>@order.TBL_MASTER_PRO_ENTRY.PRO_NAME</td>
                                                    <td>@order.TBL_MASTER_PRO_ENTRY.PRO_PRICE</td>
                                                    <td>@order.MP_CODE</td>

                                                </tr>
                                                totalBill = totalBill + @Convert.ToInt32(order.TBL_MASTER_PRO_ENTRY.PRO_PRICE);
                                            }
                                        </tbody>
                                    </table>
                                    <span class="pull-right" style="margin-right:100px;"><strong>Total Bill :  </strong> @totalBill</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            }
        }
        else
        {
            <div class="panel-body">
                <h3 style="color:red;">Empty!</h3>
            </div>

        }
    </div>
</div>

@*Desing Bootdtrap Modal With Order Form*@

<div class="modal fade" id="newOrderModal">
    <div class="modal-dialog modal-lg" style=" width: 900px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h4>Add New Order</h4>
            </div>
            <form id="NewOrderForm">
                <div class="modal-body">
                    @*Customer Details*@
                    <h5 style="color:#ff6347">Customer Details</h5>
                    <hr />
                    <div class="form-horizontal">
                        <input type="hidden" id="CustomerId" />
                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Customer Name
                            </label>
                            <div class="col-md-4">
                                <input type="text" id="name" name="name" placeholder="Customer Name" class="form-control" />
                            </div>
                            <label class="control-label col-md-2">
                                Address
                            </label>
                            <div class="col-md-4">
                                <input type="text" id="address" name="address" placeholder="Customer Address" class="form-control" />
                            </div>
                        </div>
                    </div>

                    @*Order Details*@
                    <h5 style="margin-top:10px;color:#ff6347">Order Details</h5>
                    <hr />
                    <div class="form-horizontal">
                        <input type="hidden" id="OrderId" />
                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Product Name
                            </label>
                            <div class="col-md-4">
                                <input type="text" id="productName" name="productName" placeholder="Product Name" class="form-control" />
                            </div>
                            <label class="control-label col-md-2">
                                Price
                            </label>
                            <div class="col-md-4">
                                <input type="number" id="price" name="price" placeholder="Product Price" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Quantity
                            </label>
                            <div class="col-md-4">
                                <input type="number" id="quantity" name="quantity" placeholder="Quantity" class="form-control" />
                            </div>
                            <div class="col-md-2 col-lg-offset-4">
                                <a id="addToList" class="btn btn-primary">Add To List</a>
                            </div>
                        </div>

                        <table id="detailsTable" class="table">
                            <thead>
                                <tr>
                                    <th style="width:30%">Product</th>
                                    <th style="width:20%">Unit Price</th>
                                    <th style="width:15%">Quantity</th>
                                    <th style="width:25%">Amount</th>
                                    <th style="width:10%"></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button id="saveOrder" type="submit" class="btn btn-danger">Save Order</button>
                </div>
            </form>
        </div>
    </div>
</div>






<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">

    $(window).load(function () {
        $("#newOrderModal").modal();
    });


    //Show Modal.
    function addNewOrder() {
        $("#newOrderModal").modal();
    }
    //Add Multiple Order.
    $("#addToList").click(function (e) {
        e.preventDefault();

        if ($.trim($("#productName").val()) == "" || $.trim($("#price").val()) == "" || $.trim($("#quantity").val()) == "") return;

        var productName = $("#productName").val(),
            price = $("#price").val(),
            quantity = $("#quantity").val(),
            detailsTableBody = $("#detailsTable tbody");

        var productItem = '<tr><td>' + productName + '</td><td>' + quantity + '</td><td>' + price + '</td><td>' + (parseFloat(price) * parseInt(quantity)) + '</td><td><a data-itemId="0" href="#" class="deleteItem">Remove</a></td></tr>';
        detailsTableBody.append(productItem);
        clearItem();
    });
    //After Add A New Order In The List, Clear Clean The Form For Add More Order.
    function clearItem() {
        $("#productName").val('');
        $("#price").val('');
        $("#quantity").val('');
    }
    // After Add A New Order In The List, If You Want, You Can Remove It.
    $(document).on('click', 'a.deleteItem', function (e) {
        e.preventDefault();
        var $self = $(this);
        if ($(this).attr('data-itemId') == "0") {
            $(this).parents('tr').css("background-color", "#ff6347").fadeOut(800, function () {
                $(this).remove();
            });
        }
    });
    //After Click Save Button Pass All Data View To Controller For Save Database
    function saveOrder(data) {
        return $.ajax({
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            type: 'POST',
            url: "/Orders/SaveOrder",
            data: data,
            success: function (result) {
                alert(result);
                location.reload();
            },
            error: function () {
                alert("Error!")
            }
        });
    }
    //Collect Multiple Order List For Pass To Controller
    $("#saveOrder").click(function (e) {
        e.preventDefault();

        var orderArr = [];
        orderArr.length = 0;

        $.each($("#detailsTable tbody tr"), function () {
            orderArr.push({
                productName: $(this).find('td:eq(0)').html(),
                quantity: $(this).find('td:eq(1)').html(),
                price: $(this).find('td:eq(2)').html(),
                amount: $(this).find('td:eq(3)').html()
            });
        });


        var data = JSON.stringify({
            name: $("#name").val(),
            address: $("#address").val(),
            order: orderArr
        });

        $.when(saveOrder(data)).then(function (response) {
            console.log(response);
        }).fail(function (err) {
            console.log(err);
        });
    });
</script>